[package]
name = "weetbeats"
description = "A tiny, fun, free music maker."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
weetbeats-engine.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde.workspace = true
rtrb.workspace = true
cpal = "0.18"
